import os

MLFLOW_TRACKING_URI="https://mlflow.ai.ftech.ai"
MLFLOW_TRACKING_USERNAME="admin"
MLFLOW_TRACKING_PASSWORD=""

# MODEL_REGISTRY_USER=os.getenv("MODEL_REGISTRY_USER")
# MODEL_REGISTRY_PASS=os.getenv("MODEL_REGISTRY_PASS")